services:
  - type: web
    name: monopoly-one
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: ddllke0fj
      - key: CLOUDINARY_API_KEY
        value: 181174798558466
      - key: CLOUDINARY_API_SECRET
        value: oJst_7ZvCBsaWMqDMIMcri_DRtU
      - key: RESEND_API_KEY
        sync: false
